on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'
      - name: Build
        run: |
          brew install rsync
          ./build.sh auto x86_64
          ./build.sh auto aarch64
        env:
          DARWIN_SDK_VERSION: ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            output/darwin-linux-x86_64.artifactbundle.zip
            output/darwin-linux-aarch64.artifactbundle.zip
